name: nestify
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  awesome_bottom_bar: ^1.2.4
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.2.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_inappwebview: ^6.0.0
  flutter_pannable_rating_bar: ^2.7.2+1
  font_awesome_icon_class: ^0.0.6
  get: ^4.6.6
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  path: ^1.9.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"

  image_path: "assets/icons/house.png"

  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
